from enum import Enum


class InteractionType(str, Enum):
    USER = "user"
    MODEL = "model"
    TOOL = "tool"


class CategoriaClasificacion(str, Enum):
    CLIENTE_POTENCIAL = "CLIENTE_POTENCIAL"
    CLIENTE_ACTIVO = "CLIENTE_ACTIVO"
    TRANSPORTISTA_TERCERO = "TRANSPORTISTA_TERCERO"
    PROVEEDOR_POTENCIAL = "PROVEEDOR_POTENCIAL"
    USUARIO_ADMINISTRATIVO = "USUARIO_ADMINISTRATIVO"
    CANDIDATO_A_EMPLEO = "CANDIDATO_A_EMPLEO"


class TipoDeServicio(str, Enum):
    IMPORTACION = "IMPORTACION"
    EXPORTACION = "EXPORTACION"
    DISTRIBUCION = "DISTRIBUCION"
    ALMACENAMIENTO = "ALMACENAMIENTO"
    ITR = "ITR"  # Recibo de Traslado de Intercambio
